apiVersion: v1
kind: Service
metadata:
  name: functions 
  namespace: statefun
spec:
  type: ClusterIP
  ports:
    - name: endpoint
      port: 8000
  selector:
    app: statefun
    component: functions 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: functions
  namespace: statefun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefun
      component: functions 
  template:
    metadata:
      labels:
        app: statefun
        component: functions 
    spec:
      containers:
        - name: functions 
          image: functions 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: endpoint
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60

