# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showcase_custom_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='showcase_custom_types.proto',
  package='org.apache.flink.statefun.playground.showcase',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bshowcase_custom_types.proto\x12-org.apache.flink.statefun.playground.showcase\"}\n\x0bUserProfile\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12.\n\x13\x66\x61vourite_ice_cream\x18\x02 \x01(\tR\x11\x66\x61vouriteIceCream\x12*\n\x11\x66\x61vourite_tv_show\x18\x03 \x01(\tR\x0f\x66\x61vouriteTvShowb\x06proto3')
)




_USERPROFILE = _descriptor.Descriptor(
  name='UserProfile',
  full_name='org.apache.flink.statefun.playground.showcase.UserProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.apache.flink.statefun.playground.showcase.UserProfile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='favourite_ice_cream', full_name='org.apache.flink.statefun.playground.showcase.UserProfile.favourite_ice_cream', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='favouriteIceCream', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='favourite_tv_show', full_name='org.apache.flink.statefun.playground.showcase.UserProfile.favourite_tv_show', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='favouriteTvShow', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['UserProfile'] = _USERPROFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), dict(
  DESCRIPTOR = _USERPROFILE,
  __module__ = 'showcase_custom_types_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.flink.statefun.playground.showcase.UserProfile)
  ))
_sym_db.RegisterMessage(UserProfile)


# @@protoc_insertion_point(module_scope)
